part of 'theme.dart';

final FColors neutralLightColors = FColors(
  brightness: .light,
  systemOverlayStyle: .dark,
  barrier: const Color(0x33000000),
  background: const Color(0xFFFFFFFF),
  foreground: const Color(0xFF0A0A0A),
  primary: const Color(0xFF171717),
  primaryForeground: const Color(0xFFFAFAFA),
  secondary: const Color(0xFFF5F5F5),
  secondaryForeground: const Color(0xFF171717),
  muted: const Color(0xFFF5F5F5),
  mutedForeground: const Color(0xFF666666),
  destructive: const Color(0xFFE7000B),
  destructiveForeground: const Color(0xFFFAFAFA),
  error: const Color(0xFFE7000B),
  errorForeground: const Color(0xFFFAFAFA),
  card: const Color(0xFFFFFFFF),
  border: const Color(0xFFE5E5E5),
);

final FColors neutralDarkColors = FColors(
  brightness: .dark,
  systemOverlayStyle: .light,
  barrier: const Color(0x7A000000),
  background: const Color(0xFF0A0A0A),
  foreground: const Color(0xFFFAFAFA),
  primary: const Color(0xFFE5E5E5),
  primaryForeground: const Color(0xFF171717),
  secondary: const Color(0xFF262626),
  secondaryForeground: const Color(0xFFFAFAFA),
  muted: const Color(0xFF262626),
  mutedForeground: const Color(0xFFA1A1A1),
  destructive: const Color(0xFFFF6467),
  destructiveForeground: const Color(0xFF171717),
  error: const Color(0xFFFF6467),
  errorForeground: const Color(0xFF171717),
  card: const Color(0xFF171717),
  border: const Color(0x1AFFFFFF),
);

final FColors oceanLightColors = FColors(
  brightness: .light,
  systemOverlayStyle: .dark,
  barrier: const Color(0x33000000),
  background: const Color(0xFFFFFFFF),
  foreground: const Color(0xFF090B0C),
  primary: const Color(0xFF1447E6),
  primaryForeground: const Color(0xFFEFF6FF),
  secondary: const Color(0xFFF1F3F3),
  secondaryForeground: const Color(0xFF161B1D),
  muted: const Color(0xFFF1F3F3),
  mutedForeground: const Color(0xFF5A696D),
  destructive: const Color(0xFFE7000B),
  destructiveForeground: const Color(0xFFFAFAFA),
  error: const Color(0xFFE7000B),
  errorForeground: const Color(0xFFFAFAFA),
  card: const Color(0xFFFFFFFF),
  border: const Color(0xFFE3E7E8),
);

final FColors oceanDarkColors = FColors(
  brightness: .dark,
  systemOverlayStyle: .light,
  barrier: const Color(0x7A000000),
  background: const Color(0xFF090B0C),
  foreground: const Color(0xFFF9FBFB),
  primary: const Color(0xFF193CB8),
  primaryForeground: const Color(0xFFEFF6FF),
  secondary: const Color(0xFF22292B),
  secondaryForeground: const Color(0xFFF9FBFB),
  muted: const Color(0xFF22292B),
  mutedForeground: const Color(0xFF9CA8AB),
  destructive: const Color(0xFFFF6467),
  destructiveForeground: const Color(0xFF171717),
  error: const Color(0xFFFF6467),
  errorForeground: const Color(0xFF171717),
  card: const Color(0xFF161B1D),
  border: const Color(0x1AFFFFFF),
);

final FColors forestLightColors = FColors(
  brightness: .light,
  systemOverlayStyle: .dark,
  barrier: const Color(0x33000000),
  background: const Color(0xFFFFFFFF),
  foreground: const Color(0xFF0C0C09),
  primary: const Color(0xFF007A55),
  primaryForeground: const Color(0xFFECFDF5),
  secondary: const Color(0xFFF4F4F0),
  secondaryForeground: const Color(0xFF1D1D16),
  muted: const Color(0xFFF4F4F0),
  mutedForeground: const Color(0xFF666653),
  destructive: const Color(0xFFE7000B),
  destructiveForeground: const Color(0xFFFAFAFA),
  error: const Color(0xFFE7000B),
  errorForeground: const Color(0xFFFAFAFA),
  card: const Color(0xFFFFFFFF),
  border: const Color(0xFFE8E8E3),
);

final FColors forestDarkColors = FColors(
  brightness: .dark,
  systemOverlayStyle: .light,
  barrier: const Color(0x7A000000),
  background: const Color(0xFF0C0C09),
  foreground: const Color(0xFFFBFBF9),
  primary: const Color(0xFF006045),
  primaryForeground: const Color(0xFFECFDF5),
  secondary: const Color(0xFF2B2B22),
  secondaryForeground: const Color(0xFFFBFBF9),
  muted: const Color(0xFF2B2B22),
  mutedForeground: const Color(0xFFABAB9C),
  destructive: const Color(0xFFFF6467),
  destructiveForeground: const Color(0xFF171717),
  error: const Color(0xFFFF6467),
  errorForeground: const Color(0xFF171717),
  card: const Color(0xFF1D1D16),
  border: const Color(0x1AFFFFFF),
);
