part of 'theme.dart';

// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Style tokens and theme extensions for the generated theme.
FStyle _style({
  required FColors colors,
  required FTypography typography,
  required bool touch,
  required FBorderRadius borderRadius,
}) {
  final focusedOutlineStyle = FFocusedOutlineStyle(
    color: colors.primary,
    borderRadius: borderRadius.md,
  );
  return FStyle(
    formFieldStyle: .inherit(
      colors: colors,
      typography: typography,
      touch: touch,
    ),
    focusedOutlineStyle: focusedOutlineStyle,
    sizes: FSizes.inherit(touch: touch),
    iconStyle: IconThemeData(
      color: colors.foreground,
      size: typography.body.lg.fontSize,
    ),
    tappableStyle: FTappableStyle(),
    borderRadius: borderRadius,
    borderWidth: 1,
    pagePadding: const .symmetric(vertical: 8, horizontal: 12),
    shadow: const [
      BoxShadow(color: Color(0x0d000000), offset: Offset(0, 1), blurRadius: 2),
    ],
    extensions: [
      AGridStyle.inherit(
        colors: colors,
        typography: typography,
        borderRadius: borderRadius,
        focusedOutlineStyle: focusedOutlineStyle,
      ),
    ],
  );
}
