name: admin9_app_flutter
description: "Admin9 App Starter for Android and iOS."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.2
  flutter: '>=3.47.2'

dependencies:
  auto_route: ^11.1.0
  easy_localization: ^3.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.4.2
  forui: ^0.26.0
  material_ui: ^1.0.0
  shared_preferences: ^2.5.5

dev_dependencies:
  auto_route_generator: ^10.6.0
  build_runner: ^2.16.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  forui_cli: ^0.26.0
  integration_test:
    sdk: flutter
  shared_preferences_platform_interface: ^2.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
